### ISSUE TITLE
Programma/Calendario eventi

### ISSUE THREAD

**Issue by giampiero7** [CoderDojoMilano/coderdojomilano.github.io#12]
Modificare il calendario, magari trovando una soluzione più bella al posto del google calendar e inserire link a registrazioni

**Comment by previ** [comment]
Io propongo che ogni evento futuro sia un post, e al posto del google calendar sia presente un elenco di eventi.
L'elenco può anche essere impaginato come una tabella.
Quando poi l'evento è "passato", si cambia categoria al post facendolo diventare "evento passato".

Che ne pensi?

**Comment by giampiero7** [comment]
Sì, immaginavo anche io qualcosa di simile...

**Comment by lordkada** [comment]
+1

**Comment by lordkada** [comment]
Tendenzialmente farei che il calendario eventi sia una paginetta a parte accessibile dal menù in alto oppure dalla call-to-action in home page (quella a metà pagina circa, tanto per intendersi).

**Comment by previ** [comment]
Ho rivisto un po' i menù: ora sono più simili al vecchio sito, ma secondo me è anche più chiaro.
In pratica ho aggiunto qualche menù dropdown, so che è meno usabile ma altrimenti non saprei come linkare le varie pagine.
