### ISSUE TITLE
Aggiungere pagina "i nostri mentors"

### ISSUE THREAD

**Issue by previ** [CoderDojoMilano/coderdojomilano.github.io#14]
Riprendere la pagina presente sul sito old con la presentazione dei mentor

**Comment by previ** [comment]
Aggiunta, per ora presenti Angelo ed io, se ok la completo con tutti i mentor.

**Comment by lordkada** [comment]
Per quanto mi riguarda, come prima approssimazione ci siamo... la questione "styling" (colori, etc), secondo me deve essere rivista un po' per tutte le sezioni/pagine e potremmo rimandarlo a più avanti (ora ci occupiamo dei contenuti/funzionalità) e per questo motivo ho creato la issue #17.

**Comment by previ** [comment]
Aggiornata con tutti i mentor attualmente presenti sul sito cdm.
Bisognerebbe aggiungere i nuovi, ne mancano diversi.

**Comment by lordkada** [comment]
Visto, ottimo.. 
Penso che sarà un'ottima occasione per fare aggiungere anche un po' di contenuti ai nuovi arrivati... e magari per far sì che ciascuno eventualmente riveda il proprio profilo :-)
