### ISSUE TITLE
Pagina "diventa mentor"

### ISSUE THREAD

**Issue by previ** [CoderDojoMilano/coderdojomilano.github.io#15]
Creare pagina "diventa mentor" con form che invii una mail all'indirizzo delle applications.

**Comment by lordkada** [comment]
Penso che questa pagina sia concettualmente simile a quella dei contatti. Tendenzialmente aspetterei di chiudere #13 in modo da avere un approccio unico e già collaudato. Dopodiché sarà poco più che un copia ed incolla
