### ISSUE TITLE
Look & feel

### ISSUE THREAD

**Issue by lordkada** [CoderDojoMilano/coderdojomilano.github.io#17]
Questa è una issue "placehoder" per tutte le considerazioni/commit che riguardano il look & feel del sito (colori, rendering su mobile, etc).

**Comment by previ** [comment]
Ho fatto qualche modifica minima per rendere il sito più gradevole:
- tolta l'ombra sui testi (troppo pesante imho)
- colore sfondo sempre bianco (l'azzurro di prima, sempre secondo me, era troppo sparato)

**Comment by lordkada** [comment]
Memo: c'è da fare un bel lavoro di sistemazione soprattutto per quanto riguarda il rendering su mobile.. 
Prendo spunto anche per i menu del #12, su mobile non funzionano bene (penso che si debba risolvere con la visualizzazione diretta dei sottomenu, ovvero senza click, nel caso di media piccoli).
