### ISSUE TITLE
Immagini e link nella sezione tutorial sono rotti

### ISSUE THREAD

**Issue by lordkada** [CoderDojoMilano/coderdojomilano.github.io#30]
Verificare le immagini ed i link della sezione, es: acchiappa il cappello

**Comment by lordkada** [comment]
@previ non abbiamo inserito le immagini di wp relative ai tutorial... tu hai un backup?

**Comment by previ** [comment]
Cerco...

Il sab 16 apr 2016, 14:43 Carlo Alberto Degli Atti <notifications@github.com>
ha scritto:

**Comment by acquadrod** [comment]
mancano anche i pdf delle sushi card html, sono puntamenti ad upload wordpress

**Comment by lordkada** [comment]
Sono 404 anche i documenti gdrive in: http://coderdojomilano.it/tutorials/2014-04-07-scratch-base-1-acchiappa-luovo/
