### ISSUE TITLE
Link Evenbrite per registrazione evento 11 giugno

### ISSUE THREAD

**Issue by stepanz70** [CoderDojoMilano/coderdojomilano.github.io#35]
Ciao, seguendo il consiglio di CA provo a fare la mia prima Issue su GitHub.
Segue il link Eventbrite alla pagina di registrazione al prossimo evento

[https://www.eventbrite.it/e/biglietti-coderdojo-milano-tag-11-giugno-2016-25683269350](url)

**Comment by lordkada** [comment]
@stepanz70 molto bene! Visto che alla fine non è difficile... :-)

**Comment by stepanz70** [comment]
Beh, sei stato decisamente motivante.

Stefano
Il 31/mag/2016 15:24, "Carlo Alberto Degli Atti" <notifications@github.com>
ha scritto:
