### ISSUE TITLE
Widget per Eventbrite Hackathon

### ISSUE THREAD

**Issue by stepanz70** [CoderDojoMilano/coderdojomilano.github.io#39]
Ciao, questo è l'HTML per incorporare il widget dell'evento Eventbrite di Hackathon nel sito.
`
<div style="width:100%; text-align:left;"><iframe src="//eventbrite.it/tickets-external?eid=28538434225&ref=etckt" frameborder="0" height="275" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:12px; padding:10px 0 5px; margin:2px; width:100%; text-align:left;" ><a class="powered-by-eb" style="color: #ADB0B6; text-decoration: none;" target="_blank" href="http://www.eventbrite.it/">Con tecnologia Eventbrite</a></div></div>
`

**Comment by lordkada** [comment]
@stepanz70 in linea di principio non dovrebbe servire lo snippet di codice... basta il link all'evento di eventbrite e poi il widget dovrebbe apparire in automatico! ;-)
