### ISSUE TITLE
tutorial missing image

### ISSUE THREAD

**Issue by toto-castaldi** [CoderDojoMilano/coderdojomilano.github.io#4]
nella pagina http://coderdojomilano.github.io/category/#tutorial mancano le immagini

**Comment by previ** [comment]
Le immagini possono essere configurate nei singoli post, ad esempio questo:
https://github.com/CoderDojoMilano/coderdojomilano.github.io/blob/master/_posts/2013-02-16-primo-incontro-coderdojo-milano-16-febbraio-2013.markdown

ha un parametro "thumb" con il nome dell'immagina da usare come "miniatura".
si può anche mettere sempre la stessa, modificando il template, qui:
https://github.com/CoderDojoMilano/coderdojomilano.github.io/blob/master/category.html

**Comment by toto-castaldi** [comment]
https://github.com/CoderDojoMilano/coderdojomilano.github.io/commit/c8a5b7f9dfa628dc7aa8e1057846cb7d24ea728d fixed
