### ISSUE TITLE
Link Evenbrite per Evento Discovery Channel (K2 - Bullismo)

### ISSUE THREAD

**Issue by stepanz70** [CoderDojoMilano/coderdojomilano.github.io#45]
Ciao,
questo è il link alla pagina di prenotazione su Evenbrite
[https://www.eventbrite.it/e/biglietti-bullo-e-chi-il-bullo-fa-k2-frisbee-coderdojo-milano-31775530467](url)

Grazie.

**Comment by lordkada** [comment]
Mi sembra che @fgrotta abbia aggiunto il link all'evento. Chiudo questo ticket
