### ISSUE TITLE
cambiare font, logo e colori del menù

### ISSUE THREAD

**Issue by toto-castaldi** [CoderDojoMilano/coderdojomilano.github.io#7]
come da sito attuale 

![screenshot from 2015-10-27 15 31 24](https://cloud.githubusercontent.com/assets/6171050/10761099/3237f8b0-7cc0-11e5-8ab9-8b605c7598cb.png)

**Comment by giampiero7** [comment]
Non dobbiamo attenerci al sito vecchio... un po di novità fa bene :)

**Comment by giampiero7** [comment]
Non dobbiamo attenerci al sito vecchio... un po di novità fa bene :)
